# Generated by Django 4.1.5 on 2023-08-03 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('priority', models.IntegerField()),
            ],
            options={
                'db_table': 'list_category',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('memo', models.TextField(default=None)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('dueDate', models.CharField(default=None, max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='List.category', to_field='name')),
                ('info', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='sign.info', to_field='user_id')),
            ],
        ),
    ]
