# Generated by Django 4.1.5 on 2023-08-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
