# Generated by Django 4.1.5 on 2023-02-21 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_alter_info_user_id'),
        ('List', '0002_todo_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_id',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='sign.info', to_field='user_id'),
        ),
    ]
