# Generated by Django 4.1.5 on 2023-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0003_remove_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='memo',
            field=models.TextField(default=None, null=True),
        ),
    ]
