# Generated by Django 4.1.5 on 2023-02-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0003_alter_todo_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
