# Generated by Django 4.1.5 on 2023-02-21 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0004_rename_user_id_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='info',
        ),
    ]
