# Generated by Django 4.1.5 on 2023-08-28 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_info_user_pw'),
        ('List', '0004_alter_todo_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='info',
            field=models.ForeignKey(default='user0822', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='sign.info', to_field='user_id'),
        ),
    ]
