# Generated by Django 4.1.5 on 2023-08-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_info_user_pw'),
        ('List', '0005_category_createat_category_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='info',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='sign.info', to_field='user_id'),
        ),
    ]
