# Generated by Django 4.1.5 on 2023-02-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
