# Generated by Django 4.1.5 on 2023-02-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_alter_info_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='user_pw',
            field=models.CharField(max_length=50),
        ),
    ]
