# Generated by Django 4.1.5 on 2023-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_info_user_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='user_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
